Script started on 2023-01-16 21:20:28-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;sc94@maroon06: ~/214/labs/02[01;32msc94@maroon06[00m:[01;34m~/214/labs/02[00m$ cat example6.let x
%{
#include <stdio.h>
#include <stdlib.h>           /* atoi() */
#include <string.h>           /* strcmp() */
#include "example6.tab.h"
%}
%%
[0-9]+                  yylval = atoi(yytext); return NUMBER;
heat                    return TOKHEAT;
on|off                  yylval = !strcmp(yytext,"on"); return STATE;
set                     return TOKSET;
temperature             return TOKTEMPERATURE;
humidity                return TOKHUMIDITY;

to			/*modifier? */;
\n                      /* ignore end of line */;
[ \t]+                  /* ignore whitespace */;
%%
]0;sc94@maroon06: ~/214/labs/02[01;32msc94@maroon06[00m:[01;34m~/214/labs/02[00m$ le  f cat example6.y

%{
#include <stdio.h>
#include <string.h>

/* declarations */
int yylex (void);
void yyerror (char const *);
int yyparse(void);

/* definitions */ 
void yyerror(const char *str) {
        fprintf(stderr,"error: %s\n",str);
}
 
int yywrap() {
        return 1;
} 
 
int main() {
        yyparse();
} 

%}

%token NUMBER TOKHEAT STATE TOKSET TOKTEMPERATURE TOKHUMIDITY
%%

commands: /* empty */
        | commands command
        ;

command:
        heat_switch
        | temperature_set
	| humidity_set
        ;

heat_switch:
        TOKHEAT STATE
        {
                if ($2) {  /* if STATE == 1 */
                        printf("\tHeat turned on\n");
                } else {
                        printf("\tHeat turned off\n");
                }
        }
        ;
temperature_set: 
        TOKSET TOKTEMPERATURE NUMBER
        {
                printf("\tTemperature set to %d\n",$3);
        }
        ;

humidity_set:
	TOKSET TOKHUMIDITY NUMBER
	{
		printf("\tHumidity set to %d\n",$3);
	}
	;
]0;sc94@maroon06: ~/214/labs/02[01;32msc94@maroon06[00m:[01;34m~/214/labs/02[00m$ cat example6.ylexls[Kcd  /home/cs/214/current/sc94ls[K[1@klscp project01-results /home/cs/214/current/sc94kls[K[1Plscd  /home/cs/214/current/sc94ls[Kcat example6.lex[2Py[Kflex example5 4.lex     6.lex
]0;sc94@maroon06: ~/214/labs/02[01;32msc94@maroon06[00m:[01;34m~/214/labs/02[00m$ bison -d example6.y
]0;sc94@maroon06: ~/214/labs/02[01;32msc94@maroon06[00m:[01;34m~/214/labs/02[00m$ gcc lex.yy.c example6.tab.c -o example6
]0;sc94@maroon06: ~/214/labs/02[01;32msc94@maroon06[00m:[01;34m~/214/labs/02[00m$ ./emplaing       xample  6
^[[A^[[B        set ter mperature 60
	Temperature set to 60
heat on
	Heat turned on
h set humidity to 5-0  0
	Humidity set to 50
heat off
	Heat turned off
e ^C
]0;sc94@maroon06: ~/214/labs/02[01;32msc94@maroon06[00m:[01;34m~/214/labs/02[00m$ exit
exit

Script done on 2023-01-16 21:24:10-05:00 [COMMAND_EXIT_CODE="130"]
