Script started on 2023-02-06 20:03:27-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;sc94@maroon14: ~/214/labs/05/extraCredit[01;32msc94@maroon14[00m:[01;34m~/214/labs/05/extraCredit[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (sum2Squares 3 4)user=> (def sum2Squares #(+ (* %1 %1) (* %2 %2))) user=> ([13P#(+ (* %1 %1) (* %2 %2)) 3 4)user=> [6P#(+ (* %1 %1) (* %2 %2))user=> [12P(#(* % 3) 4)user=> ([2Ptriple 4)[19@def triple (fn [x] (* x 3)))user=> ([15P(fn [] 17.2))user=> ([15@def triple (fn [x] (* x 3)))user=> [K(def triple (fn [x] (* x 3)))
[K#'user/triple
user=> [Kuser=> [Kuser=> (def triple (fn [x] (* x 3)))user=> ([12Psum2Squares 3 4)user=> (def sum2Squares #(+ (* %1 %1) (* %2 %2))) user=> ([13P#(+ (* %1 %1) (* %2 %2)) 3 4)user=> [6P#(+ (* %1 %1) (* %2 %2))user=> [12P(#(* % 3) 4)user=> [12@#(+ (* %1 %1) (* %2 %2))user=> [6@(#(+ (* %1 %1) (* %2 %2)) 3 4)user=> (def sum2Squares #(+ (* %1 %1) (* %2 %2))) user=> ([26Psum2Squares 3 4)user=> (def sum2Squares #(+ (* %1 %1) (* %2 %2))) user=> ([13P#(+ (* %1 %1) (* %2 %2)) 3 4)user=> [6P#(+ (* %1 %1) (* %2 %2))user=> [12P(#(* % 3) 4)user=> ([2Ptriple 4)user=> [K(triple 4)
12
user=> [Kuser=> [Kuser=> (triple 4)[19@def triple (fn [x] (* x 3)))user=> ([12Psum2Squares 3 4)user=> ([12@def triple (fn [x] (* x 3)))user=> [K(def triple (fn [x] (* x 3)))
#'user/triple
user=> [Kuser=> [Kuser=> (def triple (fn [x] (* x 3)))user=> (triple 4)[K[19@def triple (fn [x] (* x 3)))user=> ([12Psum2Squares 3 4)user=> (def sum2Squares #(+ (* %1 %1) (* %2 %2))) user=> ([13P#(+ (* %1 %1) (* %2 %2)) 3 4)user=> [6P#(+ (* %1 %1) (* %2 %2))user=> [12P(#(* % 3) 4)user=> [K(#(* % 3) 4)
12
user=> [Kuser=> [Kuser=> (#(* % 3) 4)user=> ([17@def triple (fn [x] (* x 3)))user=> (triple 4)[K[19@def triple (fn [x] (* x 3)))user=> ([12Psum2Squares 3 4)user=> (def sum2Squares #(+ (* %1 %1) (* %2 %2))) user=> ([13P#(+ (* %1 %1) (* %2 %2)) 3 4)user=> [K(#(+ (* %1 %1) (* %2 %2)) 3 4)
25
user=> [Kuser=> [Kuser=> (#(+ (* %1 %1) (* %2 %2)) 3 4)user=> (#([18P* % 3) 4)user=> ([17@def triple (fn [x] (* x 3)))user=> (triple 4)[K[19@def triple (fn [x] (* x 3)))user=> ([12Psum2Squares 3 4)user=> (def sum2Squares #(+ (* %1 %1) (* %2 %2))) user=> [K(def sum2Squares #(+ (* %1 %1) (* %2 %2))) 
#'user/sum2Squares
user=> [Kuser=> [Kuser=> (def sum2Squares #(+ (* %1 %1) (* %2 %2))) user=> ([13P#(+ (* %1 %1) (* %2 %2)) 3 4)user=> (#([18P* % 3) 4)user=> ([17@def triple (fn [x] (* x 3)))user=> (triple 4)[K[19@def triple (fn [x] (* x 3)))user=> ([12Psum2Squares 3 4)user=> [K(sum2Squares 3 4)
25
user=> [Kuser=> [Kuser=> 
[K]0;sc94@maroon14: ~/214/labs/05/extraCredit[01;32msc94@maroon14[00m:[01;34m~/214/labs/05/extraCredit[00m$ exit

Script done on 2023-02-06 20:04:53-05:00 [COMMAND_EXIT_CODE="0"]
