Script started on 2023-02-06 20:20:01-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;sc94@maroon14: ~/214/labs/05/extraCredit[01;32msc94@maroon14[00m:[01;34m~/214/labs/05/extraCredit[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (squareSquare 3)user=> ([27@def squareSquare #(* (* %1 %1) (* %1 %1)))user=> [K(def squareSquare #(* (* %1 %1) (* %1 %1)))
#'user/squareSquare
user=> [Kuser=> [Kuser=> (def squareSquare #(* (* %1 %1) (* %1 %1)))user=> ([27PsquareSquare 3)[1P)2)user=> [K(squareSquare 2)
16
user=> [Kuser=> [Kuser=> (squareSquare 2)user=> ([27@def squareSquare #(* (* %1 %1) (* %1 %1)))user=> ([27PsquareSquare 2)[1P)-)2)user=> [K(squareSquare -2)
16
user=> [Kuser=> [Kuser=> (squareSquare -2)[1P2)user=> ([27@def squareSquare #(* (* %1 %1) (* %1 %1)))user=> ([27PsquareSquare 3)user=> [K(squareSquare 3)
81
user=> [Kuser=> [Kuser=> (squareSquare 3)[1@-user=> [K(squareSquare -3)
81
user=> [Kuser=> [Kuser=> 
[K]0;sc94@maroon14: ~/214/labs/05/extraCredit[01;32msc94@maroon14[00m:[01;34m~/214/labs/05/extraCredit[00m$ exit

Script done on 2023-02-06 20:20:38-05:00 [COMMAND_EXIT_CODE="0"]
